### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by coffenbacher** [uswitch/bifrost#8]
Hi all -

I don't know much about Java / Clojure so it's a bit hard for me to give a great bug report. But basically, I update the default config to my S3 / Zookeeper settings and start Bifrost with Lein, per the README. 

It starts and runs, makes Zookeeper connections, reads the metadata from my Kafka nodes, writes some data in /tmp/ as expected, and then my container's supervisor comes around and kills the process for too much memory usage (I have 1.8Gb free for use by Bifrost).

Is there a way to limit the memory usage? Or do I just need more memory? If this amount of usage is unexpected, any tips on debugging?

I tried changing uploaders-n to 1 hoping that would help, but no luck.

Thanks!
-Charlie

**Comment by coffenbacher** [comment]
I tried it on a dedicated VM instead of my docker container and it works! Seems to use all available CPU and about 512Mb of RAM for my settings.

Are there any configurations that can affect this?

**Comment by tgk** [comment]
Hi @coffenbacher - sorry to hear you're having problems.

Bifrost is built to not be particularly memory-hungry, but Java can quickly suck up your resources. I'd suggest experimenting with -Xmx flag for java. The easiest way to do this would be to build the uberjar and start is with e.g. an added `-Xmx128M` flag before the `-jar` flag. This would allocate no more than 128 megs of ram for the process.

To be honest, I haven't experimented much with the memory settings, but Bifrost shouldn't be much of a hog.

The intense CPU usage arise when Bifrost has to spin up many consumers for many topics going back to the beginning of time. Once Bifrost catches up to the latest messages in the logs CPU should drop (depending on throughput in your system).

**Comment by pingles** [comment]
To follow from Thomas's comments, do you see memory climb gradually or does
it get up to that size pretty quick?

Our production instance is currently at 1.3gigs resident (3gigs virtual)
after about 4 months of operation.

As Thomas suggested, you could play with setting the heap size and see
whether that helps. If I get a chance today I'll see if I can take a look
with a profiler to see if there is a memory leak somewhere.

**Comment by coffenbacher** [comment]
Thanks for the tips! Very helpful.

Using the uberjar seemed to help, and it's helpful to know about those flags. It is working fine now. When it crashed, it seemed to explode pretty fast - felt more like there was something weird about my environment than a memory leak.

Closing this issue - Bifrost working great for me now, and I think there's enough direction here if I run into more trouble.
